name: overland_flow
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - bmi-geotiff
  - bmi-topography
  - imageio>=2.19.1
  - imageio-ffmpeg
  - jupyter
  - landlab>=2.4.1
  - matplotlib
  - numpy<1.24.0
  - tqdm
