name: overland_flow
channels:
  - conda-forge
dependencies:
  - python=3.9
  - landlab>=2.4.1
  - pymt>=1.3.1
  - pymt_topography
  - bmi-geotiff
  - cdsapi
  - numpy<1.24.0
  - xarray
  - imageio>=2.19.1
  - matplotlib
  - jupyter
  - pip
  - pip:
    - pymt-era5
    - imageio_ffmpeg

